/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author washington.osilva
 */
public class Fgts extends javax.swing.JFrame {

    /**
     * Creates new form Fgts
     */
    public Fgts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btreajustesim = new javax.swing.JButton();
        btreajustenao = new javax.swing.JButton();
        voltarFolhaPgmt = new javax.swing.JButton();
        voltarFolhaPgmt1 = new javax.swing.JButton();

        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Houve reajuste salarial no periodo?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 220, 16);

        btreajustesim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btreajustesim.setText("Sim");
        btreajustesim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreajustesimActionPerformed(evt);
            }
        });
        getContentPane().add(btreajustesim);
        btreajustesim.setBounds(20, 80, 75, 23);

        btreajustenao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btreajustenao.setText("Não");
        btreajustenao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreajustenaoActionPerformed(evt);
            }
        });
        getContentPane().add(btreajustenao);
        btreajustenao.setBounds(130, 80, 72, 23);

        voltarFolhaPgmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarFolhaPgmt.setText("Voltar");
        voltarFolhaPgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFolhaPgmtActionPerformed(evt);
            }
        });
        getContentPane().add(voltarFolhaPgmt);
        voltarFolhaPgmt.setBounds(20, 400, 72, 23);

        voltarFolhaPgmt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarFolhaPgmt1.setText("Voltar");
        voltarFolhaPgmt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFolhaPgmt1ActionPerformed(evt);
            }
        });
        getContentPane().add(voltarFolhaPgmt1);
        voltarFolhaPgmt1.setBounds(30, 230, 72, 23);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btreajustesimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreajustesimActionPerformed
       dispose();
       new Simfgts().setVisible(true);
    }//GEN-LAST:event_btreajustesimActionPerformed

    private void btreajustenaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreajustenaoActionPerformed
dispose();
new Naofgts().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btreajustenaoActionPerformed

    private void voltarFolhaPgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFolhaPgmtActionPerformed
        dispose();
        new Pergunta().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_voltarFolhaPgmtActionPerformed

    private void voltarFolhaPgmt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFolhaPgmt1ActionPerformed
        dispose();
        new Pergunta().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_voltarFolhaPgmt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fgts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btreajustenao;
    private javax.swing.JButton btreajustesim;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton voltarFolhaPgmt;
    private javax.swing.JButton voltarFolhaPgmt1;
    // End of variables declaration//GEN-END:variables
}
