
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author washington.osilva
 */
public class Folhapgt extends javax.swing.JFrame {

    /**
     * Creates new form Folhapgt
     */
    public Folhapgt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        salariofp = new javax.swing.JTextField();
        btcalcularfp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        salarioLiquido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        resultinssfp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        resultvtfp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resultirrffp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        resultfaltasfp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        faltasfp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hefp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        adiantfp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        resultHefp = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        resultvrfp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        voltarFolhaPgmt = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Salário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 50, 16);

        salariofp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(salariofp);
        salariofp.setBounds(70, 10, 64, 22);

        btcalcularfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btcalcularfp.setText("Calcular");
        btcalcularfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalcularfpActionPerformed(evt);
            }
        });
        getContentPane().add(btcalcularfp);
        btcalcularfp.setBounds(20, 100, 80, 23);

        jLabel2.setBackground(new java.awt.Color(0, 255, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Salário liquído = ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 360, 110, 16);

        salarioLiquido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(salarioLiquido);
        salarioLiquido.setBounds(110, 360, 71, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Descontos:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 80, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("INSS = ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 50, 16);

        resultinssfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(resultinssfp);
        resultinssfp.setBounds(60, 260, 64, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("VT = ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 50, 16);

        resultvtfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(resultvtfp);
        resultvtfp.setBounds(60, 290, 64, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("IRRF =");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 50, 16);

        resultirrffp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(resultirrffp);
        resultirrffp.setBounds(60, 320, 64, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("FALTAS =");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 260, 60, 16);

        resultfaltasfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(resultfaltasfp);
        resultfaltasfp.setBounds(270, 260, 64, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Faltas:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 40, 34, 16);

        faltasfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(faltasfp);
        faltasfp.setBounds(70, 40, 64, 22);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Horas extras:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 10, 90, 16);

        hefp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(hefp);
        hefp.setBounds(240, 10, 64, 22);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Adiantamento:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 40, 90, 16);

        adiantfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(adiantfp);
        adiantfp.setBounds(250, 40, 64, 22);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("H.E =");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 180, 60, 16);

        resultHefp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(resultHefp);
        resultHefp.setBounds(60, 180, 64, 22);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("ADIANTAMENTO =");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(160, 290, 110, 16);

        resultvrfp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(resultvrfp);
        resultvrfp.setBounds(270, 290, 64, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Acrescimos:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 80, 16);

        voltarFolhaPgmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarFolhaPgmt.setText("Voltar");
        voltarFolhaPgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFolhaPgmtActionPerformed(evt);
            }
        });
        getContentPane().add(voltarFolhaPgmt);
        voltarFolhaPgmt.setBounds(20, 400, 72, 23);

        setSize(new java.awt.Dimension(515, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btcalcularfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalcularfpActionPerformed
        double inss, salario = 0, horaExtra, calcHe = 0, calcFaltas = 0;
        int falta;
     
        
        try {
            String strS = salariofp.getText();
            salario = Double.parseDouble(strS);
            inss = inss(salario);
            String strResultadoInss = String.valueOf(inss);
            resultinssfp.setText(strResultadoInss);
        } catch (NumberFormatException erro) {
            //JOptionPane.showMessageDialog(null, "Digiite um valor para salário");
            //resultinssfp.requestFocus();
            inss = 0;
        }
        
        String strVt = salariofp.getText();
        double vt = Double.parseDouble(strVt);
        double v = calcVt(vt);
        String strResultadoVt = String.valueOf(v);
        resultvtfp.setText(strResultadoVt); 
       
        
        double base = salario - inss;
        double calcIrrf = irrf(base);
        String strResultadoIrrf = String.valueOf(calcIrrf);
        resultirrffp.setText(strResultadoIrrf);
        
        try {
        String strF = faltasfp.getText();
        falta = Integer.parseInt(strF);
        calcFaltas = faltas(salario, falta);
        String strResultadoFaltas = String.valueOf(calcFaltas);
        resultfaltasfp.setText(strResultadoFaltas); 
        } catch (NumberFormatException erro2){
            
            falta = 0;
        }

        try {
        String strHe = hefp.getText();
        horaExtra = Double.parseDouble(strHe);
        calcHe = horasExtras(salario, horaExtra);
        String strResultadoHe = String.valueOf(calcHe);
        resultHefp.setText(strResultadoHe);
        } catch (NumberFormatException erro3){
       
            horaExtra = 0;
        }
        
        String strAd = adiantfp.getText();
        double adiant = Double.parseDouble(strAd);
        resultvrfp.setText(strAd);
        
        
        double salarioLiq = (salario + calcHe) - calcFaltas - calcIrrf - v - inss - adiant ;
        Math.ceil(salarioLiq);
        String salarioL = String.valueOf(salarioLiq);
        salarioLiquido.setText(salarioL);

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btcalcularfpActionPerformed

    private void voltarFolhaPgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFolhaPgmtActionPerformed
dispose();
new Pergunta().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_voltarFolhaPgmtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static double inss(double salarioBruto) {
        double taxaFinal = 0.0;
        if (salarioBruto <= 1302.00) {
            taxaFinal = salarioBruto * 0.075;
        } else if (salarioBruto >= 1302.01 && salarioBruto <= 2571.29) {
            double taxa1 = 1302.00 * 0.075;
            double taxa2 = (salarioBruto - 1302.01) * 0.09;
            taxaFinal = taxa1 + taxa2;
        } else if (salarioBruto >= 2571.30 && salarioBruto <= 3856.94) {
            double taxa1 = 1302.00 * 0.075;
            double taxa2 = (2571.29 - 1302.01) * 0.09;
            double taxa3 = (salarioBruto - 2571.30) * 0.12;
            taxaFinal = taxa1 + taxa2 + taxa3;
        } else if (salarioBruto >= 3865.95) {
            double taxa1 = 1302.00 * 0.075;
            double taxa2 = (2571.29 - 1302.01) * 0.09;
            double taxa3 = (3856.94 - 2571.30) * 0.12;
            double taxa4 = (salarioBruto - 3856.94) * 0.14;
            taxaFinal = taxa1 + taxa2 + taxa3 + taxa4;
        }
        return Math.round(taxaFinal * 100.0) / 100.0;
    }

    public static double calcVt(double salario) {
        double calc = salario * 0.06;
        return Math.round(calc * 100.0) / 100.0;
    }

    public static double irrf(double salario) {
        double imposto = 0.0;
        if (salario <= 1903.98) {
            imposto = 0.0;
        } else if (salario > 1903.98 && salario <= 2826.65) {
            imposto = (0.075 * salario) - 142.80;
        } else if (salario > 2826.65 && salario <= 3751.05) {
            imposto = (0.15 * salario) - 354.80;
        } else if (salario > 3751.05 && salario <= 4664.68) {
            imposto = (0.225 * salario) - 636.13;
        } else if (salario > 4664.68) {
            imposto = (0.275 * salario) - 869.36;
        }
        return Math.round(imposto * 100.0) / 100.0;
    }

    public static double faltas(double salario, int faltas) {

        double calc = salario / 30;
        double calc2 = calc * faltas;
        return Math.round(calc2 * 100.0) / 100.0;
    }

    public static double horasExtras(double salario, double horas) {

        double calc = (salario / 30) / 8;
        double calc2 = calc * horas;
        return Math.round(calc2 * 100.0) / 100.0;

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Folhapgt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adiantfp;
    private javax.swing.JButton btcalcularfp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField faltasfp;
    private javax.swing.JTextField hefp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField resultHefp;
    private javax.swing.JTextField resultfaltasfp;
    private javax.swing.JTextField resultinssfp;
    private javax.swing.JTextField resultirrffp;
    private javax.swing.JTextField resultvrfp;
    private javax.swing.JTextField resultvtfp;
    private javax.swing.JTextField salarioLiquido;
    private javax.swing.JTextField salariofp;
    private javax.swing.JButton voltarFolhaPgmt;
    // End of variables declaration//GEN-END:variables
}
