/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author washington.osilva
 */
public class Naofgts extends javax.swing.JFrame {

    /**
     * Creates new form Naofgts
     */
    public Naofgts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pfgtsnao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sfgtsnao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        resultfgtsnao = new javax.swing.JTextField();
        btvoltarfgtsnao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Informe o periodo de trabalho em meses:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 250, 16);
        getContentPane().add(pfgtsnao);
        pfgtsnao.setBounds(20, 30, 70, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Informe o salário base:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 170, 16);

        sfgtsnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfgtsnaoActionPerformed(evt);
            }
        });
        getContentPane().add(sfgtsnao);
        sfgtsnao.setBounds(20, 90, 71, 22);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 130, 73, 23);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("O saldo acumulado do seu FGTS é:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 210, 16);

        resultfgtsnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultfgtsnaoActionPerformed(evt);
            }
        });
        getContentPane().add(resultfgtsnao);
        resultfgtsnao.setBounds(210, 170, 71, 22);

        btvoltarfgtsnao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btvoltarfgtsnao.setText("Voltar");
        btvoltarfgtsnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltarfgtsnaoActionPerformed(evt);
            }
        });
        getContentPane().add(btvoltarfgtsnao);
        btvoltarfgtsnao.setBounds(20, 220, 72, 23);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sfgtsnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfgtsnaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfgtsnaoActionPerformed

    private void resultfgtsnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultfgtsnaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultfgtsnaoActionPerformed

    private void btvoltarfgtsnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltarfgtsnaoActionPerformed
dispose();
new Fgts().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btvoltarfgtsnaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String periodo = pfgtsnao.getText();
String salario = sfgtsnao.getText();
double p = Double.parseDouble(periodo);
double s = Double.parseDouble(salario);
double x = calcFgts(p, s);
String strResultadoFgts = String.valueOf(x);
resultfgtsnao.setText(strResultadoFgts);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static double calcFgts(double periodo, double salario) {

  double calc = salario * 0.08;
  double calc2 = calc * periodo;
  return Math.round(calc2 * 100.0) / 100.0;
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Naofgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Naofgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Naofgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Naofgts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Naofgts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btvoltarfgtsnao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pfgtsnao;
    private javax.swing.JTextField resultfgtsnao;
    private javax.swing.JTextField sfgtsnao;
    // End of variables declaration//GEN-END:variables
}
