/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author washington.osilva
 */
public class Pergunta extends javax.swing.JFrame {

    /**
     * Creates new form Fgts
     */
    public Pergunta(String nome) {
        initComponents();
        nomeUsuario.setText(nome);
    }

        public Pergunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fgts = new javax.swing.JButton();
        folhapgmt = new javax.swing.JButton();
        rescisão = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Qual calculo deseja realizar?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 169, 30);

        fgts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fgts.setText("FGTS");
        fgts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgtsActionPerformed(evt);
            }
        });
        getContentPane().add(fgts);
        fgts.setBounds(20, 110, 72, 23);

        folhapgmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        folhapgmt.setText("Folha Pgt.");
        folhapgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folhapgmtActionPerformed(evt);
            }
        });
        getContentPane().add(folhapgmt);
        folhapgmt.setBounds(110, 110, 84, 23);

        rescisão.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rescisão.setText("Rescisão");
        rescisão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescisãoActionPerformed(evt);
            }
        });
        getContentPane().add(rescisão);
        rescisão.setBounds(210, 110, 90, 23);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 240, 72, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ola!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 40, 20);

        nomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(nomeUsuario);
        nomeUsuario.setBounds(60, 30, 180, 20);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fgtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgtsActionPerformed
        dispose();
        new Fgts().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_fgtsActionPerformed

    private void folhapgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folhapgmtActionPerformed
        dispose();
        new Folhapgt().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_folhapgmtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new CalculoTrabalhista().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rescisãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescisãoActionPerformed
        dispose();
        new Rescisao().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_rescisãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Folhapgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pergunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fgts;
    private javax.swing.JButton folhapgmt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JButton rescisão;
    // End of variables declaration//GEN-END:variables
}
