/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author washington.osilva
 */
public class Rescisao extends javax.swing.JFrame {

    /**
     * Creates new form Rescisao
     */
    public Rescisao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        salariorescisao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tempservrescisao = new javax.swing.JTextField();
        motivoDeslig = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calcResciao = new javax.swing.JButton();
        ResultadoRescisao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mesSaida = new javax.swing.JTextField();
        voltarFolhaPgmt = new javax.swing.JButton();
        voltarFolhaPgmt1 = new javax.swing.JButton();
        feriasvencsim = new javax.swing.JRadioButton();
        feriasvencnao = new javax.swing.JRadioButton();
        avisoprevsim = new javax.swing.JRadioButton();
        avisoprevnao = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(416, 398));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Salário base:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 110, 68, 16);
        getContentPane().add(salariorescisao);
        salariorescisao.setBounds(100, 107, 76, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("tempo de serv.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(182, 110, 84, 16);
        getContentPane().add(tempservrescisao);
        tempservrescisao.setBounds(272, 107, 81, 22);

        motivoDeslig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Pedido de demissão", "Dispensa sem justa causa", "Dispensa com justa causa" }));
        motivoDeslig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                motivoDesligItemStateChanged(evt);
            }
        });
        motivoDeslig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivoDesligActionPerformed(evt);
            }
        });
        getContentPane().add(motivoDeslig);
        motivoDeslig.setBounds(170, 9, 169, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Motivo do desligamento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 12, 138, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Possui férias vencidas?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 43, 124, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cumpriu aviso prévio?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 71, 122, 16);

        calcResciao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calcResciao.setText("Calcular");
        calcResciao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcResciaoActionPerformed(evt);
            }
        });
        getContentPane().add(calcResciao);
        calcResciao.setBounds(20, 240, 80, 23);
        getContentPane().add(ResultadoRescisao);
        ResultadoRescisao.setBounds(110, 240, 101, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mês de saida:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 158, 86, 16);

        mesSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(mesSaida);
        mesSaida.setBounds(112, 155, 64, 22);

        voltarFolhaPgmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarFolhaPgmt.setText("Voltar");
        voltarFolhaPgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFolhaPgmtActionPerformed(evt);
            }
        });
        getContentPane().add(voltarFolhaPgmt);
        voltarFolhaPgmt.setBounds(20, 400, 72, 23);

        voltarFolhaPgmt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarFolhaPgmt1.setText("Voltar");
        voltarFolhaPgmt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarFolhaPgmt1ActionPerformed(evt);
            }
        });
        getContentPane().add(voltarFolhaPgmt1);
        voltarFolhaPgmt1.setBounds(20, 310, 72, 23);

        buttonGroup1.add(feriasvencsim);
        feriasvencsim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feriasvencsim.setText("Sim");
        getContentPane().add(feriasvencsim);
        feriasvencsim.setBounds(160, 40, 60, 21);

        buttonGroup1.add(feriasvencnao);
        feriasvencnao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feriasvencnao.setText("Não");
        getContentPane().add(feriasvencnao);
        feriasvencnao.setBounds(240, 40, 50, 21);

        buttonGroup2.add(avisoprevsim);
        avisoprevsim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avisoprevsim.setText("Sim");
        getContentPane().add(avisoprevsim);
        avisoprevsim.setBounds(160, 70, 60, 21);

        buttonGroup2.add(avisoprevnao);
        avisoprevnao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avisoprevnao.setText("Não");
        getContentPane().add(avisoprevnao);
        avisoprevnao.setBounds(240, 70, 45, 21);

        setSize(new java.awt.Dimension(416, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void motivoDesligActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivoDesligActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivoDesligActionPerformed

    private void motivoDesligItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_motivoDesligItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_motivoDesligItemStateChanged

    private void calcResciaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcResciaoActionPerformed
        // TODO add your handling code here:

        double saldoSalario = 0;
        double d13 = 0;
        double feriasPro = 0;
        double tercoFerias = 0;
        double feriasAviso = 0;
        double d13Aviso = 0;
        double calcRescisao = 0;
        double feriasVenc = 0;
        double avisoPrevio = 0;

        String s = salariorescisao.getText();
        String t = tempservrescisao.getText();
        String m = mesSaida.getText();
        double salario = Double.parseDouble(s);
        double tempoServ = Double.parseDouble(t);
        double mesSaida = Double.parseDouble(m);

        String motivo;
        motivo = motivoDeslig.getSelectedItem().toString();

        if (motivo.equals("Pedido de demissão")) {

            if (feriasvencsim.isSelected() && avisoprevsim.isSelected()) {

                if (tempoServ < 12) {
                    d13 = (salario / 12) * tempoServ;
                }

                saldoSalario = salario;
                d13 = (salario / 12) * mesSaida;
                feriasPro = (salario / 12) * tempoServ;
                double d13AvisoPrevio = salario / 12;
                double feriasAvisoPrevio = salario / 12;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double desc13Aviso = inss(d13AvisoPrevio);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencnao.isSelected() && avisoprevnao.isSelected()) {

                if (tempoServ > 12) {
                    feriasPro = (salario / 12) * (tempoServ - 12);
                    d13 = (salario / 12) * mesSaida;
                } else if (tempoServ < 12) {
                    d13 = (salario / 12) * tempoServ;
                    feriasPro = (salario / 12) * tempoServ;
                }
                saldoSalario = salario;
                avisoPrevio = salario;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro - avisoPrevio - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencsim.isSelected() && avisoprevnao.isSelected()) {

                if (tempoServ > 12) {
                    d13 = (salario / 12) * mesSaida;
                } else if (tempoServ < 12) {
                    d13 = (salario / 12) * tempoServ;
                }

                feriasPro = (salario / 12) * tempoServ;
                saldoSalario = salario;
                avisoPrevio = salario;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro - avisoPrevio - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencnao.isSelected() && avisoprevsim.isSelected()) {

                if (tempoServ > 12) {
                    feriasPro = (salario / 12) * (tempoServ - 12);
                    d13 = (salario / 12) * mesSaida;
                } else if (tempoServ < 12) {
                    d13 = (salario / 12) * tempoServ;
                    feriasPro = (salario / 12) * tempoServ;
                }

                saldoSalario = salario;
                avisoPrevio = salario;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            }

        } else if (motivo.equals("Dispensa sem justa causa")) {

            if (feriasvencsim.isSelected() && avisoprevsim.isSelected()) {

                if (tempoServ > 12) {
                    d13 = (salario / 12) * mesSaida;
                } else if (tempoServ < 12) {
                    d13 = (salario / 12) * tempoServ;
                }

                feriasPro = (salario / 12) * tempoServ;
                saldoSalario = salario;
                double d13AvisoPrevio = salario / 12;
                double feriasAvisoPrevio = salario / 12;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double desc13Aviso = inss(d13AvisoPrevio);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro + d13AvisoPrevio + feriasAvisoPrevio - desc13Aviso - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencnao.isSelected() && avisoprevnao.isSelected()) {

                if (tempoServ > 12) {
                    avisoPrevio = (salario / 30) * 30 + (3 * (tempoServ / 12));
                    feriasPro = (salario / 12) * (tempoServ - 12);
                    d13 = (salario / 12) * mesSaida;
                } else if (tempoServ <= 12) {
                    d13 = (salario / 12) * tempoServ;
                    feriasPro = salario / 12 * tempoServ;
                    avisoPrevio = salario;
                }

                saldoSalario = salario;
                feriasAviso = salario / 12;
                d13Aviso = salario / 12;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro + avisoPrevio + feriasAviso + d13Aviso - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencsim.isSelected() && avisoprevnao.isSelected()) {

                if (tempoServ >= 12) {
                    avisoPrevio = (salario / 30) * 30 + (3 * (tempoServ / 12));
                    d13 = (salario / 12) * mesSaida;

                } else if (salario < 12) {
                    avisoPrevio = salario;
                    d13 = (salario / 12) * tempoServ;
                }

                saldoSalario = salario;
                feriasPro = (salario / 12) * tempoServ;
                feriasAviso = salario / 12;
                d13Aviso = salario / 12;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + avisoPrevio + tercoFeriasPro + feriasAviso + d13Aviso - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencnao.isSelected() && avisoprevsim.isSelected()) {

                if (salario < 12) {
                    d13 = (salario / 12) * tempoServ;
                }

                saldoSalario = salario;
                d13 = (salario / 12) * mesSaida;
                feriasPro = (salario / 12) * (tempoServ - 12);
                double d13AvisoPrevio = salario / 12;
                double feriasAvisoPrevio = salario / 12;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);
                double descInss13 = inss(d13);
                double desc13Aviso = inss(d13AvisoPrevio);
                double descIrrf13 = irrf(d13);

                calcRescisao = saldoSalario + d13 + feriasPro + tercoFeriasPro + d13AvisoPrevio + feriasAvisoPrevio - desc13Aviso - descInss - descIrrf - descInss13 - descIrrf13;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            }

        } else if (motivo.equals("Dispensa com justa causa")) {

            if (feriasvencsim.isSelected()) {

                saldoSalario = salario;
                feriasPro = salario;
                double tercoFeriasPro = feriasPro / 3;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);

                calcRescisao = saldoSalario + feriasPro + tercoFeriasPro - descInss - descIrrf;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            } else if (feriasvencnao.isSelected()) {

                saldoSalario = salario;
                double descInss = inss(salario);
                double descIrrf = irrf(salario);

                calcRescisao = saldoSalario - descInss - descIrrf;

                String x = String.valueOf(Math.round(calcRescisao * 100.0) / 100.0);
                ResultadoRescisao.setText(x);

            }

        }
    }//GEN-LAST:event_calcResciaoActionPerformed

    private void mesSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesSaidaActionPerformed

    private void voltarFolhaPgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFolhaPgmtActionPerformed
        dispose();
        new Pergunta().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_voltarFolhaPgmtActionPerformed

    private void voltarFolhaPgmt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarFolhaPgmt1ActionPerformed
        dispose();
        new Pergunta().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_voltarFolhaPgmt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static double inss(double salarioBruto) {
        double taxaFinal = 0.0;
        if (salarioBruto <= 1302.00) {
            taxaFinal = salarioBruto * 0.075;
        } else if (salarioBruto >= 1302.01 && salarioBruto <= 2571.29) {
            double taxa1 = 1302.00 * 0.075;
            double taxa2 = (salarioBruto - 1302.01) * 0.09;
            taxaFinal = taxa1 + taxa2;
        } else if (salarioBruto >= 2571.30 && salarioBruto <= 3856.94) {
            double taxa1 = 1302.00 * 0.075;
            double taxa2 = (2571.29 - 1302.01) * 0.09;
            double taxa3 = (salarioBruto - 2571.30) * 0.12;
            taxaFinal = taxa1 + taxa2 + taxa3;
        } else if (salarioBruto >= 3865.95) {
            double taxa1 = 1302.00 * 0.075;
            double taxa2 = (2571.29 - 1302.01) * 0.09;
            double taxa3 = (3856.94 - 2571.30) * 0.12;
            double taxa4 = (salarioBruto - 3856.94) * 0.14;
            taxaFinal = taxa1 + taxa2 + taxa3 + taxa4;
        }
        return Math.floor(taxaFinal);
    }

    public static double irrf(double salario) {
        double imposto = 0.0;
        if (salario <= 1903.98) {
            imposto = 0.0;
        } else if (salario > 1903.98 && salario <= 2826.65) {
            imposto = (0.075 * salario) - 142.80;
        } else if (salario > 2826.65 && salario <= 3751.05) {
            imposto = (0.15 * salario) - 354.80;
        } else if (salario > 3751.05 && salario <= 4664.68) {
            imposto = (0.225 * salario) - 636.13;
        } else if (salario > 4664.68) {
            imposto = (0.275 * salario) - 869.36;
        }
        return Math.ceil(imposto);
    }

    public static double calcFgts(double periodo, double salario) {

        double calc = salario * 0.08;
        double calc2 = calc * periodo;
        return Math.ceil(calc2);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rescisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rescisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rescisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rescisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rescisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ResultadoRescisao;
    private javax.swing.JRadioButton avisoprevnao;
    private javax.swing.JRadioButton avisoprevsim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton calcResciao;
    private javax.swing.JRadioButton feriasvencnao;
    private javax.swing.JRadioButton feriasvencsim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mesSaida;
    private javax.swing.JComboBox<String> motivoDeslig;
    private javax.swing.JTextField salariorescisao;
    private javax.swing.JTextField tempservrescisao;
    private javax.swing.JButton voltarFolhaPgmt;
    private javax.swing.JButton voltarFolhaPgmt1;
    // End of variables declaration//GEN-END:variables
}
